name: Compile java project

on:
  push:
    branches: [ master ]

jobs:
  Java-Ms-Dates-CI:
    runs-on: ubuntu-latest
    steps:
    - name: Preparar fuentes
      uses: actions/checkout@v2
    - name: Preparar ambiente con java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compilar proyecto
      run: mvn package 
    - name: Ejecutar en Shell
      env:
        VAR1:  asdasd
        VAR2:  asdasd
      run: |
        echo $VAR1 + $VAR2;
        pwd;
        ls -ltr;
