name: Compile java project

on:
  push:
    branches: [ master ]

jobs:
  Java-Ms-Dates-CI:
    runs-on: ubuntu-latest
    steps:
    - name: Preparar fuentes
      uses: actions/checkout@v2
    - name: Preparar ambiente con java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compilar proyecto
      run: mvn package 
    - name: Ejecutar en Shell
      env:
        VAR1:  variable-1
        VAR2:  variable-2
      run: |
        echo $VAR1 + $VAR2;
        pwd;
        ls -ltr ./target;
    - name: Analisis de codigo estatico
      uses: sonarsource/sonarcloud-github-action@master
      env: 
        GITHUB_TOKEN: ${{secrets.REPO_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
